CC:= clang
SOURCES:= $(wildcard src/*.c)
OBJECTS:= $(notdir $(SOURCES:.c=.o))

CFLAGS:= -c -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -isystem /usr/local/include/SDL2 -Iinclude
LDFLAGS:= -L/usr/local/lib
LDLIBS:= -lSDL2 -lSDL2_image

EXECUTABLE:= game

$(EXECUTABLE): $(OBJECTS)
	@echo "Linking..."
	$(CC) $(LDFLAGS) $(LDLIBS) -o $@ $^
	@echo "Linking for target $(EXECUTABLE) succeeded!"

obj/%.o: src/%.c
	@echo "Compiling:"
	$(CC) $(CFLAGS) -o $@ $<

.PHONY: clean
clean:
	-rm $(OBJECTS)
