OBJS := src/chip8.c
CC := clang
C_FLAGS := -Wall -Wextra -O2
L_FLAGS := -I/usr/local/include/SDL2 -L/usr/local/lib -lSDL2
OBJ_NAME := chip8

all: $(OBJS)
	$(CC) $(OBJS) $(C_FLAGS) $(L_FLAGS) -o $(OBJ_NAME) 
