OBJS := src/chip8.c
CC := clang
C_FLAGS := -Wall -Wextra -O2
L_FLAGS := -I/opt/homebrew/include/SDL2 -L/opt/homebrew/lib -lSDL2 -Wl,-rpath,/opt/homebrew/lib
OBJ_NAME := chip8

all: $(OBJS)
	$(CC) $(OBJS) $(C_FLAGS) $(L_FLAGS) -o $(OBJ_NAME) 
