CC := clang
TARGET  := $(notdir $(CURDIR))
BUILD   := 
SOURCE  := $(wildcard src/*.c)
OBJECT  := $(notdir $(SOURCES:.c=.o))
INCLUDE :=

CFLAGS  := -c -Wall -O3 -isystem /usr/local/include/SDL2 -Iinclude
LDFLAGS :=

all: $(BINARY)

$(BINARY): $(OBJECTS)
	$(CC) -o $@ $^

%.o:%.c
	$(CC) $(CFLAGS) -c -o $@ $^

clean:
	rm -rf $(BINARY) $(OBJECTS)
