name: Chip-8
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install SDL2
      run: |
        sudo apt-get install libsdl2-dev
    - name: Compile
      run: |
        make -f Makefile all -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          ./
