name: Chip-8
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        Makefile -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Chip-8
        path: |
          ./
