name: Libogc
on:
  push:
    branches:
    - master
jobs:
  build-wii:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: noods-wii
        path: |
          ./
