name: OSX2
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install SDL2
      run: |
        git clone --branch SDL2 --depth 1 https://github.com/libsdl-org/SDL.git
        mkdir build
        cd build 
        CC=/SDL/build-scripts/clang-fat.sh ../configure
        make
    - name: Compile
      run: |
        make -f Makefile.osx
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          ./
